// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiINw1h5h1yO_lIT4phrsrOsAhXCceq_Q',
    appId: '1:521609468615:web:7a16ba31e9b583133e3ce2',
    messagingSenderId: '521609468615',
    projectId: 'blood-f5990',
    authDomain: 'blood-f5990.firebaseapp.com',
    storageBucket: 'blood-f5990.firebasestorage.app',
    measurementId: 'G-3CF2FJW0C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMF2T_0S5YNCi2tYcBRoAzaS0lnGwsmtY',
    appId: '1:521609468615:android:38d8ff8ca3e8dc913e3ce2',
    messagingSenderId: '521609468615',
    projectId: 'blood-f5990',
    storageBucket: 'blood-f5990.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDfE9vbBlQBQ-1fajGDkvPA5WuGJLcECM',
    appId: '1:521609468615:ios:f3722c86e9871e6a3e3ce2',
    messagingSenderId: '521609468615',
    projectId: 'blood-f5990',
    storageBucket: 'blood-f5990.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonationAppFull',
  );

}