// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sheryan-variants/DarkCrimson.tsx": () => import("../components/mockups/sheryan-variants/DarkCrimson.tsx"),
  "./components/mockups/sheryan-variants/MidnightPulse.tsx": () => import("../components/mockups/sheryan-variants/MidnightPulse.tsx"),
  "./components/mockups/sheryan-variants/PureMedical.tsx": () => import("../components/mockups/sheryan-variants/PureMedical.tsx"),
  "./components/mockups/sheryan-variants/WarmCommunity.tsx": () => import("../components/mockups/sheryan-variants/WarmCommunity.tsx")
};
